### Site settings
lang: en
title: "Rindow"
description: "Rindow develops various frameworks. PHP Application Framework, Machine Learing Framework, Mathematics Libraries, etc."
#meta_description: "default meta tag description.Google does not recommend that all pages have the same description"
#meta_keywors: "default meta tag keywors.Google does not recommend that all pages have the same description"
author: "rindow&trade;"
#since: "Your site is since YYYY"
#baseurl: "/my_dir"
exclude: [ "README.md", "LICENSE", "Gemfile", "Gemfile.lock", "rindow-ghpages-bootstrap.gemspec" ]
url: "https://rindow.github.io"
#email: your-email@domain.com
#twitter_username: your_twitter_username
#github_username:  your_github_username
google_analytics_id: UA-12321104-4
#google_ad_client_id: ca-pub-XXXXXXXXXXXXXX
#google_site_verification: XXXXXXXXXXXXXXXXXXXXXXXXXXX
google_custom_search_engine_id: 000482340f7b9f4bc
#disqus_shortname: your_disqus_shortname
### Build settings
plugins:
  - jekyll-paginate
permalink: "/blog/:year/:month/:day/:title.html"
images_path: "/assets/img/"
sass:
  style: :compressed
markdown: kramdown  # kramdown or GFM
#gems: [jekyll-test-plugin, jekyll-jsonify, jekyll-assets]

### Appearance
appearance:
  theme: rindow
  ###
  ### Example to enable a wallpaper.
  ###
  #header_text_color: "brown"
  #header_image: none
  #wallpaper_image: /assets/themes/default/img/wallpaper.png
  #wallpaper_repeat: repeat

### Blog
blogpagination: true
paginate: 5
paginate_path: "blog/page:num/" # DON'T TOUCH THIS PATH.
blog:
  title: "Blog Title"
  description: "Blog description"
  title_position: article
  enable_author: true
  comment: true
  share: true
  category: true
  #sidearea:
  #  primary:
  #    widgets:
  #    - { widget: categories, caption: "Categories" }
  #    - { widget: recentposts, caption: "Recent Posts" }
  #    - { widget: subscribe, caption: "Subscribe" }
  #theme: blog

### Navigation Bar
sitesearchscript: true
navbar:
  menu:
    - caption: "Projects"
      menu:
        - { caption: "Neural Networks", link: "/neuralnetworks/index.html" }
        - { caption: "Mathematics", link: "/mathematics/index.html"}
        - { caption: "Framework", link: "/framework/index.html"}
    - { caption: "Blog", link: "/blog/" }
    - { caption: "About", link: "/about/" }

footer:
  links:
    - { caption: "About", link: "/about/" }
    #- { caption: "Sitemap", link: "/sitemap/" }

### Document collections
collections:
  neuralnetworks:
    title: "Rindow Neural Networks"
    description: "Neural networks library for PHP"
    #meta_description: "Rindow Neural Networks is a high-level neural networks library for machine learning. The goal is to be able to describe a network model in PHP as well as Python using a description method similar to Keras."
    output: true
    theme: document
    #comment: true
    #share: true
    #lang: en
    #navigator: disable
    sidearea:
      primary:
        widgets:
        - { widget: google-cse, name: sidearea, caption: "Search" }
        - { widget: navv, name: neuralnetworks, item: menu, caption: "Contents" }
  mathematics:
    title: "Rindow Mathematics"
    description: "Mathematics libraries for PHP"
    #meta_description: "An environment for vector operations suitable for scientific calculation and machine learning is provided on PHP. It also provides a PHP array extension that is optimal for vector operations."
    output: true
    theme: document
    #comment: true
    #share: true
    #lang: en
    #navigator: disable
    sidearea:
      primary:
        widgets:
        - { widget: google-cse, name: sidearea, caption: "Search" }
        - { widget: navv, name: mathematics, item: menu, caption: "Contents" }

  framework:
    title: "Rindow Framework"
    description: "PHP application framework"
    #meta_description: "The Rindow Framework is a PHP Application Framework that provides a modern programming and configuration model to all PHP programmers. Rindow is modular and your program will be modular and that is independence to PHP frameworks."
    output: true
    theme: document
    #comment: true
    #share: true
    #lang: en
    #navigator: disable
    sidearea:
      primary:
        widgets:
        - { widget: google-cse, name: sidearea, caption: "Search" }
        - { widget: navv, name: framework, item: menu, caption: "Contents" }
